version: '2'

networks:
  bridge:
    driver: bridge

services:
    web1:
        image: "xwiki:lts-postgres-tomcat"
        container_name: xw-001
        links:
            - db
        environment:
            - DB_USER=xwiki
            - DB_PASSWORD=xwiki
            - DB_DATABASE=xwiki
            - DB_HOST=xwiki-postgres-db
        volumes:
            - xwiki-data:/usr/local/xwiki
        networks:
            - bridge

    web2:
        image: "xwiki:lts-postgres-tomcat"
        container_name: xw-002
        links:
            - db
        environment:
            - DB_USER=xwiki
            - DB_PASSWORD=xwiki
            - DB_DATABASE=xwiki
            - DB_HOST=xwiki-postgres-db
        volumes:
            - xwiki-data:/usr/local/xwiki
        networks:
            - bridge

    db:
        image: "postgres:12-alpine"
        container_name: xwiki-postgres-db
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_ROOT_PASSWORD=xwiki
            - POSTGRES_PASSWORD=xwiki
            - POSTGRES_USER=xwiki
            - POSTGRES_DB=xwiki
            - POSTGRES_INITDB_ARGS="--encoding=UTF8"
        networks:
            - bridge


    webserver:
        image: nginx:alpine
        container_name: webserver
        links:
            - web2
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./cert:/etc/nginx/certs
        networks:
            - bridge
volumes:
    postgres-data: {}
    xwiki-data: {}
